cxan-website-tools-0.7.0.zip: check-sanity.xproc \
                              denorm-authors.xproc \
                              denorm-repos.xproc \
                              repo.xsd \
                              calabash.sh \
                              update-repos.sh
	zip $@ $^
